name: Regenerate package-lock.json

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  regenerate-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # You can change this to match your project

      - name: Delete existing package-lock.json and node_modules
        run: |
          rm -f package-lock.json
          rm -rf node_modules

      - name: Install dependencies to generate new package-lock.json
        run: npm install

      - name: Commit and push new lockfile
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package-lock.json
          git commit -m "Regenerate package-lock.json [CI]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
